# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

#  desc "Runs all the tests"
#  lane :test do
#    gradle(task: "test")
#  end

  desc "Build all BibApp flavors"
  lane :build do
    gradle(task: 'clean')

    gradle(task: 'bundle', flavor: 'il', build_type: 'Release')
    gradle(task: 'bundle', flavor: 'aezb', build_type: 'Release')
    gradle(task: 'bundle', flavor: 'bathueringen', build_type: 'Release')
    gradle(task: 'bundle', flavor: 'bls', build_type: 'Release')
    gradle(task: 'bundle', flavor: 'commerz', build_type: 'Release')
    gradle(task: 'bundle', flavor: 'eahjena', build_type: 'Release')
    gradle(task: 'bundle', flavor: 'hawk', build_type: 'Release')
    gradle(task: 'bundle', flavor: 'hfmweimar', build_type: 'Release')
    gradle(task: 'bundle', flavor: 'hi', build_type: 'Release')
    gradle(task: 'bundle', flavor: 'ndh', build_type: 'Release')
    gradle(task: 'bundle', flavor: 'schmalkalden', build_type: 'Release')
    gradle(task: 'bundle', flavor: 'thulb', build_type: 'Release')
    gradle(task: 'bundle', flavor: 'tubs', build_type: 'Release')
    gradle(task: 'bundle', flavor: 'ubweimar', build_type: 'Release')
    gradle(task: 'bundle', flavor: 'ufb', build_type: 'Release')
  end

  desc "Deploy all BibApp flavors to beta stage"
  lane :beta do
#    supply(package_name: 'de.eww.bibapp.il', metadata_path: 'fastlane/metadata/il', track: 'beta', aab: 'app/build/outputs/bundle/ilRelease/app-il-release.aab', skip_upload_changelogs: true, skip_upload_images: true, skip_upload_screenshots: true)
#####    supply( package_name: 'de.eww.bibapp.aezb', metadata_path: 'fastlane/metadata/aezb', track: 'beta', aab: 'app/build/outputs/bundle/aezbRelease/app-aezb-release.aab', skip_upload_changelogs: true, skip_upload_images: true, skip_upload_screenshots: true)
#    supply( package_name: 'de.eww.bibapp.bathueringen', metadata_path: 'fastlane/metadata/bathueringen', track: 'beta', aab: 'app/build/outputs/bundle/bathueringenRelease/app-bathueringen-release.aab', skip_upload_changelogs: true, skip_upload_images: true, skip_upload_screenshots: true)
#    supply( package_name: 'de.eww.bibapp.bls', metadata_path: 'fastlane/metadata/bls', track: 'beta', aab: 'app/build/outputs/bundle/blsRelease/app-bls-release.aab', skip_upload_changelogs: true, skip_upload_images: true, skip_upload_screenshots: true)
#    supply( package_name: 'de.eww.bibapp.commerz', metadata_path: 'fastlane/metadata/commerz', track: 'beta', aab: 'app/build/outputs/bundle/commerzRelease/app-commerz-release.aab', skip_upload_changelogs: true, skip_upload_images: true, skip_upload_screenshots: true)
#    supply( package_name: 'de.eww.bibapp.eahjena', metadata_path: 'fastlane/metadata/eahjena', track: 'beta', aab: 'app/build/outputs/bundle/eahjenaRelease/app-eahjena-release.aab', skip_upload_changelogs: true, skip_upload_images: true, skip_upload_screenshots: true)
#####    supply( package_name: 'de.eww.bibapp.hawk', metadata_path: 'fastlane/metadata/hawk', track: 'beta', aab: 'app/build/outputs/bundle/hawkRelease/app-hawk-release.aab', skip_upload_changelogs: true, skip_upload_images: true, skip_upload_screenshots: true)
#    supply( package_name: 'de.eww.bibapp.hfmweimar', metadata_path: 'fastlane/metadata/hfmweimar', track: 'beta', aab: 'app/build/outputs/bundle/hfmweimarRelease/app-hfmweimar-release.aab', skip_upload_changelogs: true, skip_upload_images: true, skip_upload_screenshots: true)
#####    supply( package_name: 'de.eww.bibapp.hi', metadata_path: 'fastlane/metadata/hi', track: 'beta', aab: 'app/build/outputs/bundle/hiRelease/app-hi-release.aab', skip_upload_changelogs: true, skip_upload_images: true, skip_upload_screenshots: true)
#    supply( package_name: 'de.eww.bibapp.ndh', metadata_path: 'fastlane/metadata/ndh', track: 'beta', aab: 'app/build/outputs/bundle/ndhRelease/app-ndh-release.aab', skip_upload_changelogs: true, skip_upload_images: true, skip_upload_screenshots: true)
#    supply( package_name: 'de.eww.bibapp.schmalkalden', metadata_path: 'fastlane/metadata/schmalkalden', track: 'beta', aab: 'app/build/outputs/bundle/schmalkaldenRelease/app-schmalkalden-release.aab', skip_upload_changelogs: true, skip_upload_images: true, skip_upload_screenshots: true)
#    supply( package_name: 'de.eww.bibapp.thulb', metadata_path: 'fastlane/metadata/thulb', track: 'beta', aab: 'app/build/outputs/bundle/thulbRelease/app-thulb-release.aab', skip_upload_changelogs: true, skip_upload_images: true, skip_upload_screenshots: true)
#    supply( package_name: 'de.eww.bibapp.tubs', metadata_path: 'fastlane/metadata/tubs', track: 'beta', aab: 'app/build/outputs/bundle/tubsRelease/app-tubs-release.aab', skip_upload_changelogs: true, skip_upload_images: true, skip_upload_screenshots: true)
#    supply( package_name: 'de.eww.bibapp.ubweimar', metadata_path: 'fastlane/metadata/ubweimar', track: 'beta', aab: 'app/build/outputs/bundle/ubweimarRelease/app-ubweimar-release.aab', skip_upload_changelogs: true, skip_upload_images: true, skip_upload_screenshots: true)
#####    supply( package_name: 'de.eww.bibapp.ufb', metadata_path: 'fastlane/metadata/ufb', track: 'beta', aab: 'app/build/outputs/bundle/ufbRelease/app-ufb-release.aab', skip_upload_changelogs: true, skip_upload_images: true, skip_upload_screenshots: true)
  end

end
